# netlify.toml
[build]
  publish   = "."                   # 루트 전체 서빙
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port      = 8888
  functions = "netlify/functions"

[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["mysql2"]

[build.environment]
  NODE_VERSION = "20"

# --- 라우팅 ---
# 기본 진입은 fitpl-website (메인 페이지)
[[redirects]]
  from = "/"
  to   = "/fitpl-website/index.html"
  status = 200

# fitpl-website 진입
[[redirects]]
  from = "/fitpl-website"
  to   = "/fitpl-website/index.html"
  status = 200

# 정적 파일들 (CSS, JS, 이미지 등) - 404 방지
[[redirects]]
  from = "/styles.css"
  to   = "/fitpl-website/styles.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to   = "/fitpl-website/script.js"
  status = 200
