# netlify.toml
[build]
  publish   = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  port      = 8888
  functions = "netlify/functions"

[functions]
  node_bundler          = "esbuild"
  external_node_modules = ["mysql2","dotenv"]

[build.environment]
  NODE_VERSION = "20"

# --- 라우팅 ---
# 메인 엔트리만 지정 (함수 경로는 건드리지 않음)
[[redirects]]
  from = "/"
  to   = "/fitpl-website/index.html"
  status = 200

[[redirects]]
  from = "/fitpl-website"
  to   = "/fitpl-website/index.html"
  status = 200

# (선택) 정적 파일 개별 리디렉트는 없어도 되지만, 유지해도 무방
[[redirects]]
  from = "/styles.css"
  to   = "/fitpl-website/styles.css"
  status = 200

[[redirects]]
  from = "/script.js"
  to   = "/fitpl-website/script.js"
  status = 200
